# Generated by Django 4.1.7 on 2023-03-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_productmodel_shortdescription'),
        ('cartApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddressmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shippingaddressmodel',
            name='phoneNr',
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='mainApp.productmodel'),
        ),
    ]
