# Generated by Django 4.1.7 on 2023-03-05 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='frontImgAlt',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
