# Generated by Django 4.1.7 on 2023-03-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategories',
            name='frontImg',
        ),
        migrations.RemoveField(
            model_name='productsubcategories',
            name='frontImgAlt',
        ),
    ]
