# Generated by Django 4.1.7 on 2023-03-05 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesApp', '0002_productcategories_frontimgalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='iconImg',
            field=django_resized.forms.ResizedImageField(crop=None, default=django.utils.timezone.now, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='categoryIconImage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategories',
            name='iconImgAlt',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(unique=True)),
                ('frontImg', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='categoryFrontImage/')),
                ('frontImgAlt', models.CharField(max_length=150)),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoriesApp.productcategories')),
            ],
        ),
    ]
