# Generated by Django 4.1.7 on 2023-03-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_productmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='shortDescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
