# Generated by Django 4.1.7 on 2023-03-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_storemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.storemodel'),
            preserve_default=False,
        ),
    ]
