# Generated by Django 4.1.7 on 2023-03-07 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_productmodel_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
