# Generated by Django 4.1.7 on 2023-03-08 18:39

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_storemodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='productImages/')),
                ('imageAlt', models.CharField(max_length=250)),
            ],
        ),
    ]
